mysql:
    auth:
        rootPassword: mypassword
        database: wordpress
wordpress:
    db:
        user: root
        password: mypassword
        name: wordpress
sops:
    age:
        - recipient: age1u40ahvntcm4lhr4ej4hr39ertm9nr98kfvssqtv0gqkad35u444slqgase
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpL0wweXRZY0JqV2ZoS0hs
            YTFLZ2hzTmZHSXdlcGN1Ni9qVC9na094amlZCm1XK1lpU0tBb216cFV6L2tkZ25H
            MUVuaUFJcGpGSVhiZFhBOEdwZlpMc2MKLS0tIG9PbElWRU5welJhQnRLMUpKVVpR
            dloxY1lIRUI4a2liVDZ5Z0c3dnk3NUkKzWPZdr+vMA9DwJ2jaNfMfjyxCfw/ysSA
            7VEJjs/6F8P2NkdDyLD1BvKNNnSNnGrKCiyfkP5mIwZRhkd6VBvtBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-13T20:03:32Z"
    mac: ENC[AES256_GCM,data:c4ru+MS6yXFBVbmPL7zVcUu35OAeriS/bH3MRX7LFEW9aFxJAcQq+/0fhGtWbpnES8n9npvQ1fxjadHR2kzOV3HTNul8Ifpauoi9JSLcOxwrH/HtVASSRNYhRbj/7p1eJztZ6kW1ojNvxO2PStX8hL+5BX5ExcMtNXmOYtksmTU=,iv:2iHZMQRL3VneFREdmVJH5LafDyG0phc5VWJXNYl2sIA=,tag:9KXg9b9m8IGDKr46IaD3dA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
