mysql:
    auth:
        rootPassword: mypassword
        database: wordpress
wordpress:
    db:
        user: root
        password: mypassword
        name: wordpress
sops:
    age:
        - recipient: age19rn0zfh3agua3cx4k26vnw6hjjeuamh4qpgevddes6zpn6qkcewqc0gq7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZ0o2cnR2bUxObk1FUW5L
            YXVYanBTemFSNUhaN2I4bEtBSW84Q0FZUERjCnoyRldtWjNER2ZEL2dUSzcyM0Q1
            N0FzeXJwbjM2aERUS2c1QTIzcVJNQXMKLS0tIDVRMkZzR2J4cHJSUHRzczVJUm5U
            RjMxRVJNVE5aWUdUanZJU0UvRy9jMVkKKlrAGdjurq5GXnrXysSpctoY3mH1JFi7
            X1A/3uSaqAS1gKgvr/8EZUP5cxDyvwEXkWuUr00WWhSQZRTz9ALxUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-31T08:12:06Z"
    mac: ENC[AES256_GCM,data:ll2ER67xysOJmsGea+GwqkpNVMu6zsIIzlm9AZESVgBUqCQR2gfB6U4axWtD+rKAPnQBSRDZpzq1NMSGs2PdKsjaCTx08shQm8rSTO1p9OhnRl4aAGlFiWwkXL34ct096Tt6tGQQ+3r2a3GCvONJ/BnbwXFO3yIw/XJ7wbli3sI=,iv:UzrbNgiYjPtWiQPPv871w8JgOKT1LpUtRxDiG0cpmaQ=,tag:qtWHj8FTeSkvCjO7bJjo7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
