apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
      volume.kubernetes.io/selected-node: ip-192-168-92-33.eu-central-1.compute.internal
      volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    creationTimestamp: "2025-07-13T20:15:54Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: primary
      app.kubernetes.io/instance: wordpress
      app.kubernetes.io/name: mysql
      app.kubernetes.io/part-of: mysql
    name: data-wordpress-mysql-0
    namespace: default
    resourceVersion: "550716"
    uid: a2b6ffc8-7e1e-4f70-9b4e-12dd2dc38eec
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    storageClassName: gp2
    volumeMode: Filesystem
    volumeName: pvc-a2b6ffc8-7e1e-4f70-9b4e-12dd2dc38eec
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 20Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
