replicaCount: 1

image:
  repository: wordpress
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

database:
  host: mysql-service

# DB bilgileri artık secrets/secret-values.yaml dosyasından gelecek
# db:
#   user: # şifrelenmiş dosyadan gelecek
#   password: # şifrelenmiş dosyadan gelecek  
#   name: # şifrelenmiş dosyadan gelecek

resources: {}
nodeSelector: {}
tolerations: []
affinity: []
