replicaCount: 1

image:
  repository: wordpress
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

database:
  host: mysql-service

db:
  user: root
  password: mypassword
  name: wordpress


resources: {}

nodeSelector: {}

tolerations: []

affinity: []
