replicaCount: 1

image:
  repository: wordpress
  tag: "6.4-apache"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

database:
  host: mysql

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
