apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: wordpress-project
  namespace: argocd
spec:
  description: WordPress application project
  
  # Source repositories
  sourceRepos:
  - '*'  # Allow all repos (restrict in production)
  
  # Destination clusters and namespaces
  destinations:
  - namespace: default
    server: https://kubernetes.default.svc
  - namespace: wordpress
    server: https://kubernetes.default.svc
    
  # Allowed resource types
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    
  namespaceResourceWhitelist:
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret  
  - group: ''
    kind: Service
  - group: ''
    kind: PersistentVolumeClaim
  - group: apps
    kind: Deployment
  - group: apps
    kind: StatefulSet
  - group: networking.k8s.io
    kind: Ingress
