apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
type: Opaque
stringData:
  # Bu değerler SOPS ile şifrelenmiş secret-values.yaml dosyasından gelecek
  db_user: "{{ (index .Values "db" "user") | default "root" }}"
  db_password: "{{ (index .Values "db" "password") | default "changeme" }}"
  db_name: "{{ (index .Values "db" "name") | default "wordpress" }}"
