apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
type: Opaque
stringData:
  db_user: "{{ .Values.wordpress.db.user }}"
  db_password: "{{ .Values.wordpress.db.password }}"
  db_name: "{{ .Values.wordpress.db.name }}"
