apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: wordpress
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
